eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: hanip-action
  datasource:
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5011/final_action
    username: green1
    password: spring502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true

constants:
  file:
    directory: D:/hanip/images
  jwt:
    issuer: green502@green.com
    bearer-format: JWT

    claim-key: signedUser
    secret-key: EvenTheDarkestNightWillEndAndTheSunWillRiseAgain2025!

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 900
    access-token-validity-milliseconds: 900_000

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000
    refresh-token-validity-milliseconds: 1_296_000_000


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml